apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quote-saver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/quote-saver.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: quote-saver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 