apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quote-saver
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: quote-saver
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: 'https://github.com/Malik-Ali-Awan/DevOps_Project.git'
    targetRevision: HEAD
    path: k8s
  project: default
