apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quote-saver-ingress
  namespace: quote-saver
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  
  rules:
  - host: quote-saver.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: quote-api
            port:
              number: 5000
