apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: quote-saver
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS quotes (
        id SERIAL PRIMARY KEY,
        text TEXT NOT NULL,
        author VARCHAR(255),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ); 