apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: quote-saver
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres
  POSTGRES_DB: cXVvdGVz  # quotes 