---
- name: Setup Quote Saver Environment
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Install kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install Minikube
      get_url:
        url: https://github.com/kubernetes/minikube/releases/download/v1.31.2/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Start Minikube
      command: minikube start
      become_user: "{{ ansible_user }}"

    - name: Install ArgoCD CLI
      get_url:
        url: https://github.com/argoproj/argo-cd/releases/download/v2.8.4/argocd-linux-amd64
        dest: /usr/local/bin/argocd
        mode: '0755'

    - name: Install Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.6.2/terraform_1.6.2_linux_amd64.zip
        dest: /tmp/terraform.zip
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin
        remote_src: yes 